### ISSUE TITLE
Background Click does not work

### ISSUE THREAD

**Issue by mrtylerzhou** [EasyAsABC123/Keyboard#4]
some times back click does not work

**Comment by EasyAsABC123** [comment]
@mrtylerzhou definitely a possibility sometimes it doesn't work at all for certain apps, each app is different.  This code was used for one scenario then i open sourced it, if I were to rewrite it I would likely build an injection library that has an api for keypresses

**Comment by mrtylerzhou** [comment]
thank you so much for your kindly reply. and looking forward that it will get much better
